// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPT5041fAyqyYAgcqhKLUUjIKlfaCFCJY',
    appId: '1:817590125666:web:5555f160e4d17697077d3b',
    messagingSenderId: '817590125666',
    projectId: 'globatrotter-2e059',
    authDomain: 'globatrotter-2e059.firebaseapp.com',
    storageBucket: 'globatrotter-2e059.firebasestorage.app',
    measurementId: 'G-GJZVVLJ8QD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAC_hQ3hb8rlD_CSrkiFSXu4JAVmHmpAAg',
    appId: '1:817590125666:android:c54c710481a594b6077d3b',
    messagingSenderId: '817590125666',
    projectId: 'globatrotter-2e059',
    storageBucket: 'globatrotter-2e059.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdmvpANro3JDTeotQv29hDeHL5DiD5wuo',
    appId: '1:817590125666:ios:72f642030c2e1329077d3b',
    messagingSenderId: '817590125666',
    projectId: 'globatrotter-2e059',
    storageBucket: 'globatrotter-2e059.firebasestorage.app',
    iosClientId: '817590125666-6s3346q3unap1u5t69jq27eba3k6oudc.apps.googleusercontent.com',
    iosBundleId: 'com.globetrotter.globeTrotter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdmvpANro3JDTeotQv29hDeHL5DiD5wuo',
    appId: '1:817590125666:ios:72f642030c2e1329077d3b',
    messagingSenderId: '817590125666',
    projectId: 'globatrotter-2e059',
    storageBucket: 'globatrotter-2e059.firebasestorage.app',
    iosClientId: '817590125666-6s3346q3unap1u5t69jq27eba3k6oudc.apps.googleusercontent.com',
    iosBundleId: 'com.globetrotter.globeTrotter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPT5041fAyqyYAgcqhKLUUjIKlfaCFCJY',
    appId: '1:817590125666:web:211e2b28ab7ffe09077d3b',
    messagingSenderId: '817590125666',
    projectId: 'globatrotter-2e059',
    authDomain: 'globatrotter-2e059.firebaseapp.com',
    storageBucket: 'globatrotter-2e059.firebasestorage.app',
    measurementId: 'G-FVYX8ENVG3',
  );
}
